### ISSUE TITLE
Unable to pip install this project

### ISSUE THREAD

**Issue by arpaulnet** [dominodatalab/python-domino#95] opened 2021-06-21 19:11 UTC
Commit 3c31da8437878082cb50e659da0aedce41f00419 has a syntax error in `setup.py` (line 38, I think).  The [domino data lab user docs](https://docs.dominodatalab.com/en/4.5/api/Python_wrapper_for_Domino_API.html#python-wrapper-for-domino-api) instruct users to install this project directly from github like so:

```
-e git+https://github.com/dominodatalab/python-domino.git#egg=domino
```

If users follow the docs and include that line in their projects' `requirements.txt`, their jobs, workspaces, etc. fail to startup.

**Comment by dknupp** [comment] 2021-06-21 19:13
Thanks @arpaulnet -- Looking at this now.

**Comment by dknupp** [comment] 2021-06-21 19:31
@arpaulnet -- I fixed the syntax error, and confirmed that I can install from a remote repo, with one caveat.
```
% pip install -e git+https://github.com/dknupp/python-domino.git#egg=python-domino
Looking in indexes: https://pypi.org/simple, https://ddl-pypi-reader:****@domino.jfrog.io/domino/api/pypi/pypi-local/simple
Obtaining python-domino from git+https://github.com/dknupp/python-domino.git#egg=python-domino
  Cloning https://github.com/dknupp/python-domino.git to ./fix_domino_setup/src/python-domino
  Running command git clone -q https://github.com/dknupp/python-domino.git /private/tmp/fix_domino_setup/src/python-domino
Collecting requests>=2.4.2
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting bs4==0.*,>=0.0.1
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting polling2
  Using cached polling2-0.4.6-py2.py3-none-any.whl (6.3 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.2.1-py3-none-any.whl (33 kB)
Installing collected packages: soupsieve, urllib3, idna, chardet, certifi, beautifulsoup4, requests, polling2, bs4, python-domino
  Running setup.py develop for python-domino
Successfully installed beautifulsoup4-4.9.3 bs4-0.0.1 certifi-2021.5.30 chardet-4.0.0 idna-2.10 polling2-0.4.6 python-domino-1.0.4 requests-2.25.1 soupsieve-2.2.1 urllib3-1.26.5
```
The caveat is that I had to specify `egg=python-domino` rather than `egg=domino` as shown in the docs. Can you confirm that the command as written in the docs used to work for you? (If so, I'm actually a bit confused as to how.)

**Comment by arpaulnet** [comment] 2021-06-21 20:00
@dknupp 

I'm having a hard time searching for projects containing that string.  The projects I've found thus far have this in their `requirements.txt`:
```
git+https://github.com/dominodatalab/python-domino.git
```

**Comment by dknupp** [comment] 2021-06-21 20:04
> @dknupp
> 
> I'm having a hard time searching for projects containing that string. The projects I've found thus far have this in their `requirements.txt`:
> 
> ```
> git+https://github.com/dominodatalab/python-domino.git
> ```

Thanks for checking. I'll look into the docs issue (looks like the need to be edited). In the meantime, I re-tested with the above string, and I think your use case is fixed.

That's for calling this to our attention.

**Comment by dknupp** [comment] 2021-06-22 15:44
@ddl-alexpanin -- can you close this issue?

**Closed** 2021-06-22 16:01 UTC
